### ISSUE TITLE
Error in your example

### ISSUE THREAD

**Issue by proyb6** [kenangundogan/flexible-grid#4]
There is some errors in your example?

@media (min-width: 768px)
On mobile devices (.sm-), tablets and below, the columns will automatically stack.

Tablet and below is less than 768px width.

You should consider using EM instead of PX units I think I have read if the user has change page zoom would not work. Need a bit of research.

**Comment by kenangundogan** [comment]
Thanks for the information, textual remedies were made about the narrative.

You should consider using EM instead of PX units I think I have read if the user has change page zoom would not work. Need a bit of research.**(I will consider this part**)

**Comment by proyb6** [comment]
https://engageinteractive.co.uk/blog/em-vs-rem-vs-px
https://zellwk.com/blog/media-query-units/

**Comment by kenangundogan** [comment]
thanks for the examples, i am starting to step
