### ISSUE TITLE
Any updates planned?

### ISSUE THREAD

**Issue by DanielBakovic** [kenangundogan/flexible-grid#6]
Hi,

I like your framework a lot. It's small, easy to use and powerfull. Do you plan continue woking on this project?

Best regards,
Daniel

**Comment by kenangundogan** [comment]
Hello Daniel,
Thank you for your comments.
Yes, I will continue the project. But my other project is still working on fontisto. I am coming as Fontisto GO in a short time.

Then I have a big innovation plan on Flexible Grid. I will be sharing a wide range of innovations this year

**Comment by DanielBakovic** [comment]
Thank you
